import type { CanvasPreset, CanvasProfile, CanvasTool } from "../profile";
import type { CanvasElement } from "../types";
import {
  DEFAULT_RANK_CARD_TEMPLATE,
  getRankCardRenderCacheKey,
  getRankCardTintRasterSize,
  isTintableRankCardSvgSource,
} from "../../rank-cards";

const PRESETS: CanvasPreset[] = [
  {
    name: "Modern Indigo",
    preview: "linear-gradient(135deg, #111827, #1e1b4b)",
    template: JSON.parse(JSON.stringify(DEFAULT_RANK_CARD_TEMPLATE)),
  },
  {
    name: "Neon Cyber",
    preview: "linear-gradient(135deg, #09090b, #0369a1)",
    template: {
      canvasWidth: 934,
      canvasHeight: 282,
      backgroundColor: "#030712",
      elements: [
        {
          id: "card-bg",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 262,
          fill: "linear-gradient(135deg, #030712, #082f49, #020617)",
          cornerRadius: 18,
          stroke: "rgba(6, 182, 212, 0.2)",
          strokeWidth: 1.5,
          opacity: 0.95,
          shadowColor: "rgba(6, 182, 212, 0.2)",
          shadowBlur: 20,
        },
        {
          id: "accent-bar",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 5,
          fill: "linear-gradient(90deg, #06b6d4, #3b82f6, #8b5cf6)",
          cornerRadius: 2,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 100,
          y: 141,
          radius: 56,
          borderColor: "#06b6d4",
          borderWidth: 3,
          shadowColor: "rgba(6, 182, 212, 0.5)",
          shadowBlur: 15,
        },
        {
          id: "name-text",
          type: "text",
          x: 195,
          y: 105,
          text: "{displayName}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#ffffff",
          align: "left",
        },
        {
          id: "user-tag",
          type: "text",
          x: 195,
          y: 140,
          text: "@{username}",
          fontSize: 15,
          fontFamily: "sans-serif",
          fill: "#38bdf8",
          align: "left",
        },
        {
          id: "rank-label",
          type: "text",
          x: 690,
          y: 85,
          text: "RANK",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#06b6d4",
          align: "right",
        },
        {
          id: "rank-value",
          type: "text",
          x: 740,
          y: 83,
          text: "#{rank}",
          fontSize: 26,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#38bdf8",
          align: "right",
        },
        {
          id: "level-label",
          type: "text",
          x: 820,
          y: 85,
          text: "LEVEL",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#3b82f6",
          align: "right",
        },
        {
          id: "level-value",
          type: "text",
          x: 875,
          y: 83,
          text: "{level}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#60a5fa",
          align: "right",
        },
        {
          id: "xp-counter",
          type: "text",
          x: 875,
          y: 170,
          text: "{current_xp} / {next_xp} XP",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#94a3b8",
          align: "right",
        },
        {
          id: "xp-progress",
          type: "progressbar",
          x: 195,
          y: 195,
          width: 680,
          height: 18,
          cornerRadius: 9,
          trackColor: "rgba(255, 255, 255, 0.08)",
          fill: "linear-gradient(90deg, #06b6d4, #3b82f6, #8b5cf6)",
          shadowColor: "rgba(6, 182, 212, 0.4)",
          shadowBlur: 10,
        },
      ],
    },
  },
  {
    name: "Sunset Blaze",
    preview: "linear-gradient(135deg, #18181b, #831843)",
    template: {
      canvasWidth: 934,
      canvasHeight: 282,
      backgroundColor: "#18181b",
      elements: [
        {
          id: "card-bg",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 262,
          fill: "linear-gradient(135deg, #18181b, #4c0519, #1c1917)",
          cornerRadius: 18,
          stroke: "rgba(249, 115, 22, 0.2)",
          strokeWidth: 1.5,
          opacity: 0.95,
          shadowColor: "rgba(236, 72, 153, 0.2)",
          shadowBlur: 20,
        },
        {
          id: "accent-bar",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 5,
          fill: "linear-gradient(90deg, #f97316, #ec4899, #f43f5e)",
          cornerRadius: 2,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 100,
          y: 141,
          radius: 56,
          borderColor: "#f97316",
          borderWidth: 3,
          shadowColor: "rgba(249, 115, 22, 0.5)",
          shadowBlur: 15,
        },
        {
          id: "name-text",
          type: "text",
          x: 195,
          y: 105,
          text: "{displayName}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#ffffff",
          align: "left",
        },
        {
          id: "user-tag",
          type: "text",
          x: 195,
          y: 140,
          text: "@{username}",
          fontSize: 15,
          fontFamily: "sans-serif",
          fill: "#fdba74",
          align: "left",
        },
        {
          id: "rank-label",
          type: "text",
          x: 690,
          y: 85,
          text: "RANK",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#f97316",
          align: "right",
        },
        {
          id: "rank-value",
          type: "text",
          x: 740,
          y: 83,
          text: "#{rank}",
          fontSize: 26,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#fb923c",
          align: "right",
        },
        {
          id: "level-label",
          type: "text",
          x: 820,
          y: 85,
          text: "LEVEL",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#ec4899",
          align: "right",
        },
        {
          id: "level-value",
          type: "text",
          x: 875,
          y: 83,
          text: "{level}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#f472b6",
          align: "right",
        },
        {
          id: "xp-counter",
          type: "text",
          x: 875,
          y: 170,
          text: "{current_xp} / {next_xp} XP",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#94a3b8",
          align: "right",
        },
        {
          id: "xp-progress",
          type: "progressbar",
          x: 195,
          y: 195,
          width: 680,
          height: 18,
          cornerRadius: 9,
          trackColor: "rgba(255, 255, 255, 0.08)",
          fill: "linear-gradient(90deg, #f97316, #ec4899, #f43f5e)",
          shadowColor: "rgba(249, 115, 22, 0.4)",
          shadowBlur: 10,
        },
      ],
    },
  },
  {
    name: "Emerald Forest",
    preview: "linear-gradient(135deg, #064e3b, #022c22)",
    template: {
      canvasWidth: 934,
      canvasHeight: 282,
      backgroundColor: "#022c22",
      elements: [
        {
          id: "card-bg",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 262,
          fill: "linear-gradient(135deg, #022c22, #064e3b, #041f18)",
          cornerRadius: 18,
          stroke: "rgba(16, 185, 129, 0.2)",
          strokeWidth: 1.5,
          opacity: 0.95,
          shadowColor: "rgba(16, 185, 129, 0.2)",
          shadowBlur: 20,
        },
        {
          id: "accent-bar",
          type: "rect",
          x: 10,
          y: 10,
          width: 914,
          height: 5,
          fill: "linear-gradient(90deg, #10b981, #34d399, #6ee7b7)",
          cornerRadius: 2,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 100,
          y: 141,
          radius: 56,
          borderColor: "#10b981",
          borderWidth: 3,
          shadowColor: "rgba(16, 185, 129, 0.5)",
          shadowBlur: 15,
        },
        {
          id: "name-text",
          type: "text",
          x: 195,
          y: 105,
          text: "{displayName}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#ffffff",
          align: "left",
        },
        {
          id: "user-tag",
          type: "text",
          x: 195,
          y: 140,
          text: "@{username}",
          fontSize: 15,
          fontFamily: "sans-serif",
          fill: "#6ee7b7",
          align: "left",
        },
        {
          id: "rank-label",
          type: "text",
          x: 690,
          y: 85,
          text: "RANK",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#10b981",
          align: "right",
        },
        {
          id: "rank-value",
          type: "text",
          x: 740,
          y: 83,
          text: "#{rank}",
          fontSize: 26,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#34d399",
          align: "right",
        },
        {
          id: "level-label",
          type: "text",
          x: 820,
          y: 85,
          text: "LEVEL",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#059669",
          align: "right",
        },
        {
          id: "level-value",
          type: "text",
          x: 875,
          y: 83,
          text: "{level}",
          fontSize: 28,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#6ee7b7",
          align: "right",
        },
        {
          id: "xp-counter",
          type: "text",
          x: 875,
          y: 170,
          text: "{current_xp} / {next_xp} XP",
          fontSize: 14,
          fontFamily: "sans-serif",
          fontStyle: "bold",
          fill: "#94a3b8",
          align: "right",
        },
        {
          id: "xp-progress",
          type: "progressbar",
          x: 195,
          y: 195,
          width: 680,
          height: 18,
          cornerRadius: 9,
          trackColor: "rgba(255, 255, 255, 0.08)",
          fill: "linear-gradient(90deg, #10b981, #34d399, #6ee7b7)",
          shadowColor: "rgba(16, 185, 129, 0.4)",
          shadowBlur: 10,
        },
      ],
    },
  },
];

const TOOLS: CanvasTool[] = [
  {
    type: "text",
    icon: "i-heroicons-bars-3-bottom-left",
    label: "Text",
    color: "text-amber-400",
  },
  {
    type: "progressbar",
    icon: "i-heroicons-chart-bar",
    label: "XP Progress Bar",
    color: "text-indigo-400",
  },
  {
    type: "avatar",
    icon: "i-heroicons-user-circle",
    label: "Avatar",
    color: "text-purple-400",
  },
  {
    type: "rect",
    icon: "i-heroicons-stop",
    label: "Rectangle",
    color: "text-blue-400",
  },
  {
    type: "circle",
    icon: "i-heroicons-sun",
    label: "Circle",
    color: "text-cyan-400",
  },
  {
    type: "triangle",
    icon: "i-heroicons-play",
    label: "Triangle",
    color: "text-teal-400",
  },
  {
    type: "star",
    icon: "i-heroicons-star",
    label: "Star",
    color: "text-yellow-400",
  },
  {
    type: "line",
    icon: "i-heroicons-minus",
    label: "Line / Arrow",
    color: "text-lime-400",
  },
  {
    type: "image",
    icon: "i-heroicons-photo",
    label: "Custom Image",
    color: "text-sky-400",
  },
];

export const rankCardProfile: CanvasProfile = {
  id: "rank-card",
  noun: "rank card template",
  logPrefix: "[RankCardEditor]",
  tools: TOOLS,
  presets: PRESETS,
  defaultTemplate: () => JSON.parse(JSON.stringify(DEFAULT_RANK_CARD_TEMPLATE)),
  placeholders: [
    "{displayName}",
    "{username}",
    "{rank}",
    "{level}",
    "{current_xp}",
    "{next_xp}",
    "{xp}",
    "{progress_percent}",
    "{messages}",
    "{server_name}",
    "{member_count}",
    "{tag}",
  ],
  textHint: "Use {displayName}, {level}, etc.",
  sample: [
    [/\{displayName\}/g, "Alex Johnson"],
    [/\{username\}/g, "alex_j"],
    [/\{tag\}/g, "alex_j#0001"],
    [/\{server_name\}/g, "My Server"],
    [/\{level\}/g, "14"],
    [/\{rank\}/g, "3"],
    [/\{current_xp\}/g, "1,240"],
    [/\{next_xp\}/g, "2,050"],
    [/\{xp\}/g, "8,450"],
    [/\{progress_percent\}/g, "65%"],
    [/\{messages\}/g, "342"],
    [/\{member_count\}/g, "1,250"],
  ],
  shadow: "all",
  fallback: {
    rectFill: "#111827",
    circleFill: "#6366f1",
    starFill: "#eab308",
    lineStroke: "#6366f1",
    textAlign: "left",
    avatarRadius: 56,
    avatarBorder: "#818cf8",
  },
  newElement: (type, cx, cy) => {
    const defs: Record<string, Partial<CanvasElement>> = {
      text: {
        type: "text",
        x: cx,
        y: cy,
        text: "New Text",
        fontSize: 24,
        fontFamily: "sans-serif",
        fontStyle: "",
        fill: "#ffffff",
        align: "left",
        opacity: 1,
      },
      progressbar: {
        type: "progressbar",
        x: 195,
        y: 195,
        width: 680,
        height: 18,
        cornerRadius: 9,
        trackColor: "rgba(255, 255, 255, 0.08)",
        fill: "linear-gradient(90deg, #6366f1, #a855f7, #ec4899)",
        opacity: 1,
      },
      rect: {
        type: "rect",
        x: cx - 75,
        y: cy - 50,
        width: 150,
        height: 100,
        fill: "#1e1b4b",
        opacity: 1,
        cornerRadius: 8,
      },
      circle: {
        type: "circle",
        x: cx,
        y: cy,
        radius: 50,
        fill: "#6366f1",
        opacity: 1,
      },
      triangle: {
        type: "triangle",
        x: cx,
        y: cy,
        radius: 50,
        fill: "#374151",
        opacity: 1,
      },
      star: {
        type: "star",
        x: cx,
        y: cy,
        numPoints: 5,
        innerRadius: 25,
        outerRadius: 50,
        fill: "#eab308",
        opacity: 1,
      },
      line: {
        type: "line",
        x: cx,
        y: cy,
        points: [-60, 0, 60, 0],
        stroke: "#6366f1",
        strokeWidth: 3,
        opacity: 1,
        arrow: false,
      },
      avatar: {
        type: "avatar",
        x: 100,
        y: 141,
        radius: 56,
        borderColor: "#818cf8",
        borderWidth: 3,
        opacity: 1,
      },
    };
    return defs[type];
  },
  uploads: { background: "/api/xp/upload-bg", image: "/api/xp/upload-image" },
  images: {
    isTintableSvg: isTintableRankCardSvgSource,
    tintRasterSize: getRankCardTintRasterSize,
    renderKey: getRankCardRenderCacheKey,
  },
};
