import type { CanvasPreset, CanvasProfile, CanvasTool } from "../profile";
import type { CanvasElement, CanvasTemplate } from "../types";
import {
  getWelcomeImageRenderCacheKey,
  getWelcomeImageTintRasterSize,
  isTintableWelcomeSvgSource,
} from "../../welcome-images";

const DEFAULT_TEMPLATE: CanvasTemplate = {
  canvasWidth: 1024,
  canvasHeight: 500,
  backgroundColor: "#1a1a2e",
  elements: [
    {
      id: "bg-overlay",
      type: "rect",
      x: 0,
      y: 0,
      width: 1024,
      height: 500,
      fill: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)",
      opacity: 1,
    },
    {
      id: "decoration-top",
      type: "rect",
      x: 0,
      y: 0,
      width: 1024,
      height: 4,
      fill: "linear-gradient(90deg, #6366f1, #a78bfa, #c084fc)",
      opacity: 1,
    },
    {
      id: "avatar",
      type: "avatar",
      x: 512,
      y: 155,
      radius: 80,
      borderColor: "#a78bfa",
      borderWidth: 4,
    },
    {
      id: "welcome-label",
      type: "text",
      x: 512,
      y: 280,
      text: "WELCOME",
      fontSize: 44,
      fontFamily: "sans-serif",
      fontStyle: "bold",
      fill: "#ffffff",
      align: "center",
    },
    {
      id: "username-text",
      type: "text",
      x: 512,
      y: 340,
      text: "{username}",
      fontSize: 30,
      fontFamily: "sans-serif",
      fill: "#a78bfa",
      align: "center",
    },
    {
      id: "server-text",
      type: "text",
      x: 512,
      y: 395,
      text: "to {server_name}",
      fontSize: 20,
      fontFamily: "sans-serif",
      fill: "#9ca3af",
      align: "center",
    },
    {
      id: "member-count",
      type: "text",
      x: 512,
      y: 450,
      text: "Member #{member_count}",
      fontSize: 16,
      fontFamily: "sans-serif",
      fill: "#6b7280",
      align: "center",
    },
  ],
};

const PRESETS: CanvasPreset[] = [
  {
    name: "Classic",
    preview: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)",
    template: JSON.parse(JSON.stringify(DEFAULT_TEMPLATE)),
  },
  {
    name: "Sunset",
    preview: "linear-gradient(135deg, #f12711, #f5af19)",
    template: {
      canvasWidth: 1024, canvasHeight: 500, backgroundColor: "#1a0a00",
      elements: [
        { id: "bg-overlay", type: "rect", x: 0, y: 0, width: 1024, height: 500, fill: "linear-gradient(135deg, #1a0a00, #4a1a00, #1a0a00)", opacity: 1 },
        { id: "accent-top", type: "rect", x: 0, y: 0, width: 1024, height: 4, fill: "linear-gradient(90deg, #f12711, #f5af19, #f12711)", opacity: 1 },
        { id: "avatar", type: "avatar", x: 512, y: 155, radius: 80, borderColor: "#f5af19", borderWidth: 4 },
        { id: "welcome-label", type: "text", x: 512, y: 280, text: "WELCOME", fontSize: 44, fontFamily: "sans-serif", fontStyle: "bold", fill: "#ffffff", align: "center" },
        { id: "username-text", type: "text", x: 512, y: 340, text: "{username}", fontSize: 30, fontFamily: "sans-serif", fill: "#f5af19", align: "center" },
        { id: "server-text", type: "text", x: 512, y: 395, text: "to {server_name}", fontSize: 20, fontFamily: "sans-serif", fill: "#d4a574", align: "center" },
        { id: "member-count", type: "text", x: 512, y: 450, text: "Member #{member_count}", fontSize: 16, fontFamily: "sans-serif", fill: "#8b6914", align: "center" },
      ],
    },
  },
  {
    name: "Neon",
    preview: "linear-gradient(135deg, #0a0a0a, #1a0033, #0a0a0a)",
    template: {
      canvasWidth: 1024, canvasHeight: 500, backgroundColor: "#0a0a0a",
      elements: [
        { id: "bg-overlay", type: "rect", x: 0, y: 0, width: 1024, height: 500, fill: "linear-gradient(135deg, #0a0a0a, #1a0033, #0a0a0a)", opacity: 1 },
        { id: "accent-top", type: "rect", x: 0, y: 0, width: 1024, height: 3, fill: "linear-gradient(90deg, #00ff88, #00ccff, #ff00ff)", opacity: 1 },
        { id: "accent-bot", type: "rect", x: 0, y: 497, width: 1024, height: 3, fill: "linear-gradient(90deg, #ff00ff, #00ccff, #00ff88)", opacity: 1 },
        { id: "avatar", type: "avatar", x: 512, y: 155, radius: 80, borderColor: "#00ccff", borderWidth: 4 },
        { id: "welcome-label", type: "text", x: 512, y: 280, text: "WELCOME", fontSize: 44, fontFamily: "sans-serif", fontStyle: "bold", fill: "#00ff88", align: "center" },
        { id: "username-text", type: "text", x: 512, y: 340, text: "{username}", fontSize: 30, fontFamily: "sans-serif", fill: "#00ccff", align: "center" },
        { id: "server-text", type: "text", x: 512, y: 395, text: "to {server_name}", fontSize: 20, fontFamily: "sans-serif", fill: "#cc66ff", align: "center" },
        { id: "member-count", type: "text", x: 512, y: 450, text: "Member #{member_count}", fontSize: 16, fontFamily: "sans-serif", fill: "#555577", align: "center" },
      ],
    },
  },
  {
    name: "Minimal",
    preview: "linear-gradient(135deg, #18181b, #27272a)",
    template: {
      canvasWidth: 1024, canvasHeight: 500, backgroundColor: "#18181b",
      elements: [
        { id: "avatar", type: "avatar", x: 512, y: 175, radius: 70, borderColor: "#3f3f46", borderWidth: 3 },
        { id: "username-text", type: "text", x: 512, y: 300, text: "{username}", fontSize: 32, fontFamily: "sans-serif", fontStyle: "bold", fill: "#fafafa", align: "center" },
        { id: "server-text", type: "text", x: 512, y: 360, text: "joined {server_name}", fontSize: 18, fontFamily: "sans-serif", fill: "#71717a", align: "center" },
      ],
    },
  },
];

const TOOLS: CanvasTool[] = [
  {
    type: "text",
    icon: "i-lucide-type",
    label: "Text",
    color: "text-violet-400",
  },
  {
    type: "rect",
    icon: "i-lucide-square",
    label: "Rectangle",
    color: "text-blue-400",
  },
  {
    type: "circle",
    icon: "i-lucide-circle",
    label: "Circle",
    color: "text-cyan-400",
  },
  {
    type: "triangle",
    icon: "i-lucide-triangle",
    label: "Triangle",
    color: "text-amber-400",
  },
  {
    type: "star",
    icon: "i-lucide-star",
    label: "Star",
    color: "text-yellow-400",
  },
  {
    type: "line",
    icon: "i-lucide-minus",
    label: "Line / Arrow",
    color: "text-lime-400",
  },
  {
    type: "image",
    icon: "i-lucide-image",
    label: "Image",
    color: "text-sky-400",
  },
  {
    type: "avatar",
    icon: "i-lucide-circle-user",
    label: "Avatar",
    color: "text-pink-400",
  },
];

export const welcomeProfile: CanvasProfile = {
  id: "welcome",
  noun: "welcome template",
  logPrefix: "[Welcome image editor]",
  tools: TOOLS,
  presets: PRESETS,
  defaultTemplate: () => JSON.parse(JSON.stringify(DEFAULT_TEMPLATE)),
  placeholders: ["{username}", "{displayname}", "{tag}", "{server_name}", "{member_count}"],
  textHint: "Use {username}, etc.",
  sample: [
    [/\{username\}/g, "NewUser"],
    [/\{displayname\}/g, "New User"],
    [/\{tag\}/g, "NewUser#0001"],
    [/\{server_name\}/g, "My Server"],
    [/\{member_count\}/g, "42"],
  ],
  shadow: "image",
  fallback: {
    rectFill: "#ffffff",
    circleFill: "#ffffff",
    starFill: "#374151",
    lineStroke: "#e4e4e7",
    textAlign: "center",
    avatarRadius: 64,
    avatarBorder: "#ffffff",
  },
  newElement: (type, cx, cy) => {
    const defs: Record<string, Partial<CanvasElement>> = {
      text: {
        type: "text",
        x: cx,
        y: cy,
        text: "New Text",
        fontSize: 24,
        fontFamily: "sans-serif",
        fontStyle: "",
        fill: "#ffffff",
        align: "center",
        opacity: 1,
      },
      rect: {
        type: "rect",
        x: cx - 75,
        y: cy - 50,
        width: 150,
        height: 100,
        fill: "#374151",
        opacity: 1,
        cornerRadius: 8,
      },
      circle: {
        type: "circle",
        x: cx,
        y: cy,
        radius: 50,
        fill: "#4f46e5",
        opacity: 1,
      },
      triangle: {
        type: "triangle",
        x: cx,
        y: cy,
        radius: 50,
        fill: "#374151",
        opacity: 1,
      },
      star: {
        type: "star",
        x: cx,
        y: cy,
        numPoints: 5,
        innerRadius: 25,
        outerRadius: 50,
        fill: "#374151",
        opacity: 1,
      },
      line: {
        type: "line",
        x: cx,
        y: cy,
        points: [-60, 0, 60, 0],
        stroke: "#e4e4e7",
        strokeWidth: 3,
        opacity: 1,
        arrow: false,
      },
      avatar: {
        type: "avatar",
        x: cx,
        y: cy - 80,
        radius: 64,
        borderColor: "#a78bfa",
        borderWidth: 3,
        opacity: 1,
      },
    };
    return defs[type];
  },
  uploads: { background: "/api/welcome/upload-bg", image: "/api/welcome/upload-image" },
  images: {
    isTintableSvg: isTintableWelcomeSvgSource,
    tintRasterSize: getWelcomeImageTintRasterSize,
    renderKey: getWelcomeImageRenderCacheKey,
  },
};
